services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    image: ghcr.io/${{ github.repository }}:test
    command: sh -c "python manage.py migrate && python manage.py test"
    environment:
      - DB_NAME=test_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - SECRET_KEY=test-secret
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy
