name: Quality Gate

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  quality-check:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --only main --no-root --no-interaction

      - name: Run Ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --output-format=github"

      - name: Run Ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"

      - name: Run Django tests
        env:
          DB_NAME: test_db
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          SECRET_KEY: test-secret-key-for-ci
          DEBUG: "True"
          ALLOWED_HOSTS: localhost,127.0.0.1
        run: |
          python manage.py migrate
          python manage.py test
